server:
  port: 8888

spring:
  application:
    name: config-service
  profiles:
    active: native  # native, subversion, git
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/properties/
        default-label: properties

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    instanceId: ${spring.cloud.client.hostname}:${server.port}:${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
  endpoint:
    env:
      enabled: true
    health:
      enabled: false

