server:
  port: 8020

spring:
  application:
    name: admin-service
  profiles:
    active: dev
  security:
    user:
      name: admin
      password: admin

# 暴露所有actuator端点(2.0+配置方法)
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
