server:
  port: 8020

spring:
  application:
    name: admin-service
  profiles:
    active: dev
  security:
    user:
      name: admin
      password: admin
  cloud:
    nacos:
      config:
        server-addr: 1.117.200.16:8848
        file-extension: yml
      discovery:
        server-addr: 1.117.200.16:8848
        service: ${spring.application.name}
        namespace: ${spring.profiles.active}
      username: nacos
      password: *

# 暴露所有actuator端点(2.0+配置方法)
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
