server:
  port: 8020

spring:
  application:
    name: admin-service
  security:
    user:
      name: admin
      password: admin

# 暴露所有actuator端点(2.0+配置方法)
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
      fetch-registry: true #是否从服务注册中心获取可用的服务清单，默认为true，PS：服务注册好后大概需要30秒才能被发现？？？ß
  instance:
    instanceId: ${spring.cloud.client.hostname}:${server.port}:${spring.application.name}:${spring.application.instance_id:${random.value}}
    metadata-map:
      "user.name": ${spring.security.user.name}
      "user.password": ${spring.security.user.password}