spring:
  boot:  #spirng admin 配置
    admin:
      client:
        url: http://127.0.0.1:8020  # admin server 地址
        username: admin
        password: admin
        instance:
          service-url: http://127.0.0.1:8010 # 当前系统地址
          name: ${spring.application.name}
          metadata:
            user.name: ${spring.security.user.name}
            user.password: ${spring.security.user.password}
  zipkin:
    base-url: http://127.0.0.1:8060  #指定zipkin的服务端，用于发送链路调用报告
    compression:
      enabled: true
  sleuth:
    sampler:
      probability: 1  #采样率，值为[0,1]之间的任意实数，这里代表100%采集报告

  redis:
    database: 0
    host: 1.117.200.16
    port: 6379
    password: *
    timeout: 30s
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数
        max-wait: -1s   # 连接池最大阻塞等待时间 负数表示没限制
        max-idle: 4 # 连接池中的最大空闲连接
        min-idle: 0  # 连接池中的最小空闲连接
    connect-timeout: 10s #连接超时时间

# 暴露所有actuator端点(2.0+配置方法)
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

# cat starter bean装配开关
cat:
  switch:
    client: true
    chain: true

