server:
  port: 8000

spring:
  application:
    name: consume-service
  cloud:
    nacos:
      config:
        server-addr: 1.117.200.16:8848
      discovery:
        server-addr: 1.117.200.16:8848
        service: ${spring.application.name}
      username: nacos
      password: flj641
  boot:  #spirng admin 配置
    admin:
      client:
        url: http://127.0.0.1:8020
        username: admin
        password: admin
        instance:
          service-url: http://127.0.0.1:8010
          name: ${spring.application.name}
          metadata:
            user.name: ${spring.security.user.name}
            user.password: ${spring.security.user.password}
  zipkin:
    base-url: http://127.0.0.1:8060  #指定zipkin的服务端，用于发送链路调用报告
    compression:
      enabled: true
  sleuth:
    sampler:
      probability: 1  #采样率，值为[0,1]之间的任意实数，这里代表100%采集报告

# 暴露所有actuator端点(2.0+配置方法)
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

