server:
  port: 8000

spring:
  application:
    name: consume-service
  cloud:
    config:
      profile: test
      discovery:
        enabled: true
      uri: http://127.0.0.1:8888/
      name: ${spring.application.name}
  boot:  #spirng admin 配置
    admin:
      client:
        url: http://127.0.0.1:8020/
        username: admin
        password: admin
        instance:
          prefer-ip: true
  zipkin:
    base-url: http://127.0.0.1:8060  #指定zipkin的服务端，用于发送链路调用报告
    compression:
      enabled: true
  sleuth:
    sampler:
      probability: 1  #采样率，值为[0,1]之间的任意实数，这里代表100%采集报告

# 暴露所有actuator端点(2.0+配置方法)
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
      fetch-registry: true #是否从服务注册中心获取可用的服务清单，默认为true，PS：服务注册好后大概需要30秒才能被发现？？？ß
  instance:
    instanceId: ${spring.cloud.client.hostname}:${server.port}:${spring.application.name}:${spring.application.instance_id:${random.value}}

feign:
  hystrix:
    enabled: true # 启动hystrix熔断机制